source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDBSharedDateFormatter_Example', :exclusive => true do
  pod "CDBSharedDateFormatter", :path => "../"
end

target 'CDBSharedDateFormatter_Tests', :exclusive => true do
  pod "CDBSharedDateFormatter", :path => "../"

  
end
